[debug]
address = "127.0.0.1"
port = 8000
workers = 2
keep_alive = 5
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 80
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
limits = { forms = 32768 }

[default.databases.sqlite_logs]
url = "./PizzaDB.sqlite"